quarkus:
  package:
    jar:
      enabled: true
  http:
    port: 9091
    test-port: 0
  devservices:
    enabled: false
  kafka:
    devservice:
      enabled: false
  datasource:
    db-kind: mysql
    username: root
    password: 123456789
    reactive:
      url: vertx-reactive:mysql://localhost:3308/bd_order_shipping
  hibernate-orm:
    database:
      generation: none
      version-check:
        enabled: false


kafka:
  bootstrap:
    servers: PLAINTEXT://localhost:19092

mp:
  messaging:
    connector:
      smallrye-kafka:
        schema:
          registry:
            url: http://localhost:8081
        auto:
          register:
            schemas: false
        use:
          latest:
            version: true
    outgoing:
      order-shipping-emitter:
        topic: order-shipping-topic
        connector: smallrye-kafka

#mp:
#  messaging:
#    outgoing:
#      order-shipping-emitter:
#        connector: smallrye-kafka
#        topic: order-shipping-topic
#        bootstrap:
#          servers: ${CONFIG_KAFKA_BROKERS:PLAINTEXT://localhost:19092,PLAINTEXT://localhost:29092}
#        schema:
#          registry:
#            url: ${CONFIG_SCHEMA_REGISTRY_URL:http://localhost:8081}
#        auto:
#          register:
#            schemas: true # Utilizarlo solo en Desarrollo o local
#        use:
#          latest:
#            version: true